Allow for org.glassfish.jersey.servlet.ServletContainer in web.xml
eclipse-ee4j/jersey pull request #4615
Opened 2020-10-20 08:24 UTC by jansupol

without init parameters and without the Application subclass in the app

Signed-off-by: Jan Supol <jan.supol@oracle.com>

2020-10-20 09:00 UTC, senivam requested changes

2020-10-20 15:07 UTC, jansupol commented on containers/jersey-servlet/src/main/java/org/glassfish/jersey/servlet/init/JerseyServletContainerInitializer.java
> +                    if (sr != null) {
The instance is created anyways, ServletRegistration is just a reference to that instance. But sure, I'll make it final. I'd better have the set without nulls, not to catch NPE when later modified.

2020-10-20 16:23 UTC, senivam approved these changes
LGTM

2020-10-26 12:14 UTC, Verdent approved these changes

2020-10-27 11:18 UTC, merged