Make JAX-B API optional
eclipse-ee4j/jersey pull request #4634
Opened 2020-11-09 22:00 UTC by jansupol

Signed-off-by: Jan Supol <jan.supol@oracle.com>

2020-11-11 12:58 UTC, senivam requested changes

2020-11-11 12:58 UTC, senivam commented on core-server/pom.xml
> +        <dependency>
please consider changing copyright year in this file

2020-11-11 12:58 UTC, senivam commented on connectors/jetty-connector/pom.xml
> +        <dependency>
please consider changing copyright year in this file

2020-11-11 12:58 UTC, senivam commented on examples/bookstore-webapp/pom.xml
> +        <dependency>
please consider updating copyright year in this file

2020-11-11 12:58 UTC, senivam commented on examples/https-clientserver-grizzly/pom.xml
> +        <dependency>
please consider updating copyright year in this file

2020-11-11 12:58 UTC, senivam commented on examples/jaxb/pom.xml
> +                <dependency>
please consider updating copyright year in this file

2020-11-11 12:58 UTC, senivam commented on examples/multipart-webapp/pom.xml
> +        <dependency>
please consider updating copyright year in this file

2020-11-11 12:58 UTC, senivam commented on ext/bean-validation/pom.xml
> +        <dependency>
please consider updating copyright year in this file

2020-11-11 12:58 UTC, senivam commented on ext/bean-validation/src/main/java/org/glassfish/jersey/server/validation/ValidationErrorData.java
> + * Copyright (c) 20208 Oracle and/or its affiliates. All rights reserved.
please consider fixing copyright year in this file

2020-11-11 12:58 UTC, senivam commented on ext/entity-filtering/pom.xml
> +        <dependency>
please consider updating copyright year in this file

2020-11-12 13:05 UTC, senivam approved these changes
LGTM

2020-12-02 13:13 UTC, Verdent approved these changes

2020-12-14 21:54 UTC, merged