Support arrays
eclipse-ee4j/jersey pull request #4684
Opened 2021-01-15 15:06 UTC by jbescos

Relates to this: https://github.com/eclipse-ee4j/jaxrs-api/issues/890

Primitive types are not supported. That is said here:
https://github.com/eclipse-ee4j/jaxrs-api/pull/891

> 1.  Types for which a `ParamConverter` is available via
> a registered `ParamConverterProvider`. See Javadoc for these classes for
> a registered `ParamConverterProvider`. See Javadoc for these classes for
> more information.
> more information.
> 2.  Primitive types.
> 2.  Primitive types.
> 3.  Types that have a constructor that accepts a single
> 3.  Types that have a constructor that accepts a single
> `String` argument.
> `String` argument.
> 4.  Types that have a static method named `valueOf` or
> 4.  Types that have a static method named `valueOf` or
> `fromString` with a single `String` argument that return an instance of
> `fromString` with a single `String` argument that return an instance of
> the type. If both methods are present then `valueOf` MUST be used unless
> the type. If both methods are present then `valueOf` MUST be used unless
> the type is an enum in which case `fromString` MUST be usedfootnote:[Due
> the type is an enum in which case `fromString` MUST be usedfootnote:[Due
> to limitations of the built-in `valueOf` method that is part of all Java
> to limitations of the built-in `valueOf` method that is part of all Java
> enumerations, a `fromString` method is often defined by the enum
> enumerations, a `fromString` method is often defined by the enum
> writers. Consequently, the `fromString` method is preferred when
> writers. Consequently, the `fromString` method is preferred when
> available.].
> available.].
> 5.  `List<T>`, `Set<T>`, or `SortedSet<T>`, where `T` satisfies
> 5.  `List<T>`, `Set<T>`, `SortedSet<T>` or an array `T[]`, where
> 1,3 or 4 above.
> `T` satisfies 1, 3 or 4 above.

2021-01-15 20:56 UTC, senivam commented
shouldn't it be for jakartified spec only?

2021-01-20 13:02 UTC, jansupol requested changes
Please make tests for cases 3 and 4, too.
for 4 for instance:
```
    public static class ArrayTestBean {
        private final String value;

        private ArrayTestBean(String value) {
            this.value = value;
        }

        public static ArrayTestBean fromString(String bean) {
            return new ArrayTestBean(bean);
        }

        @Override
        public String toString() {
            return value;
        }
    }

        @Path("/queryBeanArray")
        @GET
        public Response queryBeanArray(@QueryParam(PARAM_NAME) ArrayTestBean[] data) {
            StringBuilder sb = new StringBuilder(data.length);
            for (ArrayTestBean d : data) {
                sb.append(d);
            }
            return Response.ok(sb.toString()).build();
        }

        @Path("/queryBeanList")
        @GET
        public Response queryBeanList(@QueryParam(PARAM_NAME) List<ArrayTestBean> data) {
            StringBuilder sb = new StringBuilder(data.size());
            for (ArrayTestBean d : data) {
                sb.append(d);
            }
            return Response.ok(sb.toString()).build();
        }

    @Test
    public void queryBean() {
        Response expected = target("/test/queryBeanList").queryParam(PARAM_NAME, "1", "2").request().get();
        Response arrayResponse = target("/test/queryBeanArray").queryParam(PARAM_NAME, "1", "2").request().get();
        verifyStr(expected, arrayResponse);
    }
```

2021-01-20 13:28 UTC, jansupol commented
> shouldn't it be for jakartified spec only?

For 3.1, it would be a MUST. For 2.x, it is an enhancement.

2021-01-20 13:53 UTC, jbescos commented on connectors/jdk-connector/src/test/java/org/glassfish/jersey/jdk/connector/internal/ArrayParamConverterTest.java
> +/*
Good to know. By default I was adding tests in JDK connector.

2021-01-21 09:26 UTC, jbescos commented
Primitive types are supported in the last commit

2021-01-21 14:28 UTC, jansupol approved these changes

2021-01-22 07:43 UTC, senivam approved these changes

2021-01-22 07:43 UTC, merged