4 chapters of User Guide reviewed
eclipse-ee4j/jersey pull request #4711
Opened 2021-02-02 17:10 UTC by senivam

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

2021-04-12 08:41 UTC, jansupol requested changes

2021-04-12 08:41 UTC, jansupol commented on docs/src/main/docbook/jersey.ent
> +<!ENTITY helidon.version "2.1.0">
Do we have a CQ for 2.1.0?

2021-04-16 11:20 UTC, jansupol approved these changes

2021-04-19 13:33 UTC, Verdent approved these changes

2021-04-19 13:34 UTC, merged