Custom schedulers to execute @PreDestroy methods
eclipse-ee4j/jersey pull request #4716
Opened 2021-02-10 14:35 UTC by jbescos

Relates to https://github.com/eclipse-ee4j/jersey/issues/3921

2021-02-17 12:43 UTC, jansupol requested changes

2021-02-17 12:43 UTC, jansupol commented on tests/e2e-server/src/test/java/org/glassfish/jersey/tests/e2e/server/ScheduledThreadPoolExecutorProviderTest.java
> + * Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
2021

2021-02-18 13:46 UTC, jansupol approved these changes

2021-02-19 11:50 UTC, senivam approved these changes

2021-02-19 11:50 UTC, merged