User Guide: GraalVM/native-image chapter
eclipse-ee4j/jersey pull request #4802
Opened 2021-05-28 07:44 UTC by senivam

Adding a chapter to user guide about GraalVM native image support. And fixes some minor errors in other user guide pages. 

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

2021-06-01 13:24 UTC, jbescos approved these changes

2021-07-02 17:12 UTC, jansupol commented on docs/src/main/docbook/graalvm-native-image.xml
> +            Actually Jersey provides basic support for native image generation within following modules:
~Actually~ Currently.
<literal>jesey-client</literal>

2021-07-02 17:13 UTC, jansupol commented on docs/src/main/docbook/graalvm-native-image.xml
> +                <member>Download Jersey examples source codes (preferable some released version like 2.34),
~2.34~ 2.35

2021-07-02 17:23 UTC, jansupol requested changes

2021-07-02 17:23 UTC, jansupol commented on docs/src/main/docbook/graalvm-native-image.xml
> +            Another important aspect for generating of native image is proper listing of reflection classes (classes which uses reflection
I'd suggest using a spellchecker. This is the change after using one:

Another important aspect for generating the native image is the proper listing of reflection classes (classes that use reflection in an application). For those needs, there is a native image agent which helps to generate those lists automatically.

In order to generate a list of reflection classes (and JNI classes and resources), it is required to run.
And afterward, the [output_location] directory will be created with generated lists (in JSON format). Those files can be included as is into native image generation, but it's very preferable to edit them manually to reduce possible ambiguous classes listings.

2021-08-12 11:47 UTC, jansupol approved these changes

2021-08-12 11:48 UTC, merged