handle URISyntaxException in JettyHttpContainer
eclipse-ee4j/jersey pull request #4809
Opened 2021-06-14 18:50 UTC by aserkes

handle URISyntaxException in JettyHttpContainer to return 400 code instead 500 code

2021-06-16 05:54 UTC, senivam requested changes

2021-06-16 05:54 UTC, senivam commented on containers/jetty-http/src/test/java/org/glassfish/jersey/jetty/ExceptionTest.java
> +        String incorrectFragment = "&params[0]=test_status";
the incorrect line here should be replaces with that from reproducer. Bucause the current one does fail for 400 but it fails even before processing by Jersey's Jetty handler, but earlier inside Jetty container so it does not test the case.

2021-06-17 08:15 UTC, senivam commented on containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpContainer.java
> +    private static final javax.ws.rs.core.Response.Status BAD_REQUEST_STATUS = javax.ws.rs.core.Response.Status.BAD_REQUEST;
I mean you can move the ``javax.ws.rs.core.Response.Status`` part of the declaration into the ``import javax.ws.rs.core.Response.Status;`` section. Thus the whole block would look like: 

```
    private static final int INTERNAL_SERVER_ERROR = Status.INTERNAL_SERVER_ERROR.getStatusCode();
    private static final Status BAD_REQUEST_STATUS = Status.BAD_REQUEST;
```

2021-06-17 08:17 UTC, senivam requested changes
see my [comment](https://github.com/eclipse-ee4j/jersey/pull/4809/files#r653334824)

2021-06-21 10:06 UTC, senivam approved these changes

2021-06-29 07:46 UTC, jbescos approved these changes

2021-07-02 12:20 UTC, merged