HTTP/2 for Jetty connector
eclipse-ee4j/jersey pull request #5294
Opened 2023-03-24 10:06 UTC by senivam

2023-08-15 09:03 UTC, jansupol commented on connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java
> +    public HttpClient getRegisteredHttpClient(Configuration config) {
Why is this public?

2023-08-16 13:20 UTC, jansupol requested changes

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java
> +    public JettyConnector(final Client jaxrsClient, final Configuration config) {
protected

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java
> +    public HttpClient getRegisteredHttpClient(Configuration config) {
protected

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-http2-connector/src/main/java/org/glassfish/jersey/jetty/http2/connector/JettyHttp2Connector.java
> +    public HttpClientTransport initClientTransport() {
protected

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-http2-connector/src/main/java/org/glassfish/jersey/jetty/http2/connector/JettyHttp2Connector.java
> +    public HttpClient getRegisteredHttpClient(Configuration config) {
protected

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-http2-connector/src/main/java/org/glassfish/jersey/jetty/http2/connector/JettyHttp2ClientSupplier.java
> + * @since 2.40
2.41

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-http2-connector/src/main/java/org/glassfish/jersey/jetty/http2/connector/JettyHttp2Connector.java
> + * @since 2.40
2.41

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-http2-connector/src/main/java/org/glassfish/jersey/jetty/http2/connector/JettyHttp2Connector.java
> +     * @since 2.40
2.41

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-http2-connector/src/main/java/org/glassfish/jersey/jetty/http2/connector/JettyHttp2Connector.java
> +     * @since 2.40
2.41

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java
> +     * @since 2.40
2.41

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java
> +     * @since 2.40
2.41

2023-08-16 13:20 UTC, jansupol commented on connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java
> +    public HttpClientTransport initClientTransport() {
protected

2023-08-17 16:57 UTC, jansupol approved these changes

2023-08-18 12:34 UTC, jbescos approved these changes

2023-08-18 12:56 UTC, merged