UserGuide and example extended for Micrometer integration
eclipse-ee4j/jersey pull request #5427
Opened 2023-09-27 12:10 UTC by senivam

2023-10-12 05:49 UTC, jbescos approved these changes

2023-10-18 10:13 UTC, jansupol requested changes

2023-10-18 10:13 UTC, jansupol commented on examples/micrometer/src/main/java/org/glassfish/jersey/examples/micrometer/MetricsStore.java
> +import io.micrometer.core.instrument.binder.jersey.server.DefaultJerseyTagsProvider;
Use 
```
import org.glassfish.jersey.micrometer.server.DefaultJerseyTagsProvider;
import org.glassfish.jersey.micrometer.server.MetricsApplicationEventListener;
```
instead

2023-10-18 10:13 UTC, jansupol commented on examples/micrometer/src/main/java/org/glassfish/jersey/examples/micrometer/SummaryResource.java
> +                final Timer timer = store.getRegistry().get("http.shared.metrics")
Use `MetricsStore.REGISTRY_NAME` instead of `"http.shared.metrics"`

2023-10-18 12:43 UTC, jansupol approved these changes

2023-10-18 15:13 UTC, merged